import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Footer } from './components/Footer';
import { Header } from './components/Header';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { AboutMe } from './components/AboutMe';
config.autoAddCss = false;

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <AboutMe />
        {children}
        <Footer />
      </body>
    </html>
  );
}
